# infrastructure/docker/docker-compose.yml
version: "3.8"

services:
  crawler:
    build:
      context: ../..
      dockerfile: infrastructure/docker/Dockerfile
    env_file:
      - ../../.env
    volumes:
      - ../../src:/home/playwright/app/src:ro
      - ../../config:/home/playwright/app/config:ro
      - playwright-cache:/home/playwright/.cache/ms-playwright
    environment:
      - PYTHONPATH=/home/playwright/app/src
      - PLAYWRIGHT_BROWSERS_PATH=/home/playwright/.cache/ms-playwright
      - PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1
      - DISPLAY=:99
    security_opt:
      - seccomp=unconfined
    cap_add:
      - SYS_ADMIN
    working_dir: /app
    command: ["uv", "run", "scrapy", "crawl", "frontier_spider"]

    develop:
      watch:
        - action: sync+restart
          path: ../../src
          target: /app/src
          ignore:
            - "**/__pycache__"
            - "**/*.pyc"
        - action: sync+restart
          path: ../../config
          target: /app/config
          ignore:
            - "**/__pycache__"
            - "**/*.pyc"
        - action: rebuild
          path: pyproject.toml

volumes:
  playwright-cache:
