# infrastructure/docker/docker-compose.yml
version: '3.8'

services:
  crawler:
    build:
      context: ../..
      dockerfile: infrastructure/docker/Dockerfile
    env_file:
      - ../../.env
    volumes:
      - ../../src:/app/src:ro
      - ../../config:/app/config:ro

      - playwright-cache:/playwright-browsers

    environment:
      - PYTHONPATH=/app/src
      - UV_COMPILE_BYTECODE=1
      - UV_LINK_MODE=copy
      - PLAYWRIGHT_BROWSERS_PATH=/playwright-browsers
      - PYTHONUNBUFFERED=1
    working_dir: /app
    command: ["uv", "run", "scrapy", "crawl", "frontier_spider"]

    develop:
      watch:
        - action: sync+restart
          path: ../../src
          target: /app/src
          ignore:
            - "**/__pycache__"
            - "**/*.pyc"
        - action: sync+restart
          path: ../../config
          target: /app/config
          ignore:
            - "**/__pycache__"
            - "**/*.pyc"
        - action: rebuild
          path: pyproject.toml

volumes:
  playwright-cache: