categories:
  - url_seed_root_id: 0
    name: "Torino"
    description: "Borse di studio e premi di laurea UniTo"
    urls:
      - url: "https://pubblicazioni.unito.it/visualizzaperweb.php?tipo=25&p=y&C7=all&criterio35=A&criterio46=No"
        type: 1
        target_patterns:
          - ".*\\.pdf$"
          - ".*\\.pdf[^a-zA-Z].*"
          - ".*download.*pdf.*"
        seed_pattern: null
        max_depth: 0

  - url_seed_root_id: 1
    name: "Bologna"
    description: "Borse di studio e premi di laurea UniBo"
    urls:
      - url: "https://bandi.unibo.it/agevolazioni/borse?b_start:int=0"
        type: 2
        target_patterns:
          - ".pdf"
        seed_pattern: "/s/abis1/" # Pattern più preciso
        max_depth: 1
