categories:
  - name: "Bologna"
    description: "Borse di studio e premi di laurea UniBo"
    urls:
      - url: "https://bandi.unibo.it/agevolazioni/premi-laurea"
        type: 2
        target_patterns:
          - ".*\\.pdf$"
        seed_pattern: ".*/agevolazioni/premi-laurea/.*" # Aggiunto un pattern esempio per Type 2
        max_depth: 1

      - url: "https://bandi.unibo.it/agevolazioni/borse?b_start:int=20"
        type: 2
        target_patterns:
          - ".*\\.pdf$"
        seed_pattern: ".*/agevolazioni/borse/.*" # Aggiunto un pattern esempio per Type 2
        max_depth: 1

      - url: "https://bandi.unibo.it/agevolazioni/borse"
        type: 2
        target_patterns:
          - ".*\\.pdf$"
        seed_pattern: ".*/agevolazioni/borse/.*" # Aggiunto un pattern esempio per Type 2
        max_depth: 1

  - name: "Torino"
    description: "Borse di studio e premi di laurea UniTo"
    urls:
      - url: "https://webapps.unito.it/concorsiweb/visualizzaperweb.php?tipo=25&p=y&C7=all&criterio35=A&criterio46=No"
        type: 1
        target_patterns:
          - ".*\\.pdf$"
        seed_pattern: null # Type 1 non richiede seed_pattern
        max_depth: 0

      - url: "https://webapps.unito.it/concorsiweb/visualizzaperweb.php?tipo=24&p=y&C7=all&criterio35=A&criterio46=No"
        type: 1
        target_patterns:
          - ".*\\.pdf$"
        seed_pattern: null # Type 1 non richiede seed_pattern
        max_depth: 0
